export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_REQUESTED = 'FETCH_USER_REQUESTED';
export const FETCH_USER_SUCCEEDED = 'FETCH_USER_SUCCEEDED';
export const SUBMIT_TOKEN = 'SUBMIT_TOKEN';
export const SUBMIT_SURVEY = 'SUBMIT_SURVEY';
export const FETCH_SURVEYS = 'FETCH_SURVEYS';
export const FETCH_SURVEYS_REQUESTED = 'FETCH_SURVEYS_REQUESTED';
export const FETCH_SURVEYS_SUCCEEDED = 'FETCH_SURVEYS_SUCCEEDED';
